### ISSUE TITLE
New Papertrail CA bundle next week

### ISSUE THREAD

**Issue by markdascher** [outstand/docker-syslog-ng-papertrail#1]
Papertrail will be updating **papertrail-bundle.tar.gz** on **Tuesday, May 15**. The new MD5 checksum will be `23d82ae8698d41e75d1e85224d6a9ad5`, but given that we might continue updating this file from time to time, I'd recommend against simply hard-coding a new checksum. Instead, either omit the checksum entirely, or embed the entire bundle rather than downloading it. Either option ensures that Papertrail is free to update the source without breaking anyone's deployment.

**Comment by ryansch** [comment]
Wow thanks for the heads up!

**Comment by ryansch** [comment]
@markdascher Any chance you guys will move to signing releases?  It's important to me that the thing I download when building the container comes from you.

**Comment by markdascher** [comment]
Hi @ryansch!

If the verify only occurs when building a container and not as part of the deployment, then the consequences aren't as severe as I'd imagined. But for your own sanity, I'd still recommend relying on the fact that it's a secure HTTPS download and hence resistant to any third-party tampering, rather than trying to keep the MD5 checksums up-to-date.

At least for the moment, we have no plans of signing the CA bundle.

**Comment by ryansch** [comment]
It's only when building the container image.  The bundle is 'baked in' after that.

It's a docker best practice to use some sort of verification on downloaded assets.  I'll probably just keep updating the MD5 checksum as it'll be pretty obvious when it breaks.  This is where long lived signing keys are a big win.

**Comment by ryansch** [comment]
I've updated the CA bundle.
